version: "3"

services:
  webserver:
    build:
      context: docker/images/php81
    restart: 'always'
    hostname: laravel.local
    ports:
      - "80:80"
    links:
      - database
    volumes:
      - ./:/var/www/html
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/config/vhosts:/etc/apache2/sites-enabled
      - ./docker/logs/site/apache2:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9005"
      PHP_IDE_CONFIG: serverName=laravel.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
  database:
    build:
      context: "./docker/images/mysql"
    restart: 'always'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: laravel
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
